### ISSUE TITLE
Schrödingers' Dynamic Window Manager with the ever-changing title

### ISSUE THREAD

**Issue by Coalms** [slavistan/dwm-dynamicswallow-patch#1]
I'm kind of confused here
the command ` dwmswallow $WINDOWID -c firefox` works perfectly when called after I start my session but when I am writing any of the following ony my .zshrc

` dwmswallow $WINDOWID -c firefox`
 or
` for swallowed in ${toswallow[@]};do dwmswallow $WINDOWID -c $swallowed ;done`

(tried to launch them with `>> swallowlog` at the end of both commands but failed since nothing got logged down) 

or any other way writing it down  will either work or wont work (checked class case sensitiveness with `xprop` naturally),it has come to the point that sometimes my laptop will boot and dwmswallow will work for all or some of the calls but other times it doesn't work at all ,sometimes it works for a few days or in the spur of the moment and others it acts like the command being called doesn't event exist,can start working in the middle of the session out of nowhere etc.etc. 

Perhaps I am missing something or perhaps I didn't understand the patch well enough or there are other ways to do this nevertheless if anyone has a workaround to this I would be grateful

**Comment by slavistan** [comment]
I'm not sure I follow what you're tring to achieve. Open firefox everytime you open a terminal? Queue every terminal you open to swallow a future instance of firefox? May I kindly ask you to outline what you're trying to do? What's your end goal / desired behavior?

I'll try to address a few of your points in piecemeal fashion.

---

>writing any of the following ony my .zshrc
>dwmswallow $WINDOWID -c firefox

This serves no useful purpose as it will simply register each and every terminal you open to swallow the next instance of firefox _WITHOUT_ opening firefox (if multiple windows want to swallow the same future window it's last-come-first-serve). Just to make sure we're on the same page: `dwmswallow` does not run applications or open windows itself.

If you wanted to "open firefox in the terminal" you would execute (typed manually, via a shell alias, a keybind or a script)

```
dwmswallow $WINDOWID -c Firefox
firefox
```

---

>tried to launch them with >> swallowlog at the end of both commands but failed since nothing got logged down

`dwmswallow` does not produce output unless something is wrong. No news is good news.

---

>dwmswallow $WINDOWID -c firefox

Firefox's class name is **Firefox** (capital f).

---

>for swallowed in ${toswallow[@]};do dwmswallow $WINDOWID -c $swallowed >;done

Calling `dwmswallow $WINDOWID ...` (in the same terminal) repeatedly will override any previous calls. Executing this

```
dwmswallow $WINDOWID -c Firefox
dwmswallow $WINDOWID -c Zathura
```
will make the window swallow Zathura only, but not Firefox.

**Comment by slavistan** [comment]
Also, may I kindly ask you to give the issue a descriptive title? I have no clue about Batman, I don't see what a physicist has to do with dwm and even less do I understand how a .zshrc could be a snitch. Are you sure this wasn't meant to land on reddit? :)

**Comment by Coalms** [comment]
@slavistan Apologies about the title I was reading a few books before that and my mind was feeling adventurous,

Back to the issue,or to the start before than even

I have a weird bug due to my drivers for my gm965 graphics card and most things I spawn from the gui just turn invisible and stay that way, so I have to launch everything on terminal, having said that, having dwm launching everything over the terminal is rather...inconvenient so I though since this patch exist (being more convenient than the previous available swallowing patch)I wourld just invoke all the classes I want to be able to launch swallowed with a loop (so just store everything inside an array and loop through it one by one on each new terminal)

Afterwards if so I choose to launch firefox zathura thunar godot or anything else I just type it and it works.... But life is not that simple and so here we are,

I just cannot understand does the patch just break when I invoke  dwmswallow multiple times before an actual window is spawned,
Do I actually have to make aliases like firefox="dwmswallow $WINDOWID -c Firefox && firefox"

Tbh I just wanted to do it my method since its cleaner hence more easy to add more programs I want to swallow to my "array of to-swallow programmes"

Other things to state, is that i stated "IDK havent checked but .zshrc ain't no snitch"

what i really ment is I dont know havent checked(if your program produces output such as a log or not), but requesting output through zshrc to be saved to a file does not work thus zshrc ain't no snitch


Lastly when you compare someone(a) to something/one(b), else ,that someone(a) will take the most prevalent characteristics of (b) as basis for the comparison, unbeknownst to you, yourself, you just compared me to something (in essence) soulless which is insulting to say the least, I mean try comparing some random dude on the street with reddit and you are most likely going to get punched, stabbed, defiled, and set aflame for a good measure

Jokes aside that was actually hurtful to say mate at least I am trying to have a life :(

**Comment by slavistan** [comment]
I owe you an apology, good sir. The past weeks of self-inflicted uptight "professionalism" have jammed my head and I seem to have become almost deaf to humour and the finer nuances of human language. Writing documentation and conveying technical detail will do that for you. I hope you don't let yourself get slowed down by some buttoned-up stranger. Do foster this adventurous mind of yours, do keep reading those books (which books exactly - I'm curious!) and do keep those colorful issue titles coming.

Concerning the issue: if I understood you correctly you're trying to use the terminal to spawn and immediately swallow gui-programs because the other way ("spawn from the guy", as you call it) causes the windows to spawn and remain hidden. Correct? So the dwm-terminal-swallow is a hack/workaround for something else, aye?

Based on these premises I can offer you to use keybinds. Add this to your `.zshrc`:

```
bindkey -M vicmd '^X^m' accept-line-swallow # if you're using vim bindings in zsh
bindkey -M viins '^X^m' accept-line-swallow # if you're using vim bindings in zsh
bindkey '^X^m' accept-line-swallow
zle -N accept-line-swallow acceptandswallow
acceptandswallow() {
	dwmswallow $WINDOWID
	zle accept-line
}
```

If you type something into your shell such as `firefox` you how have the option of pressing **Ctrl-x, Enter** which will cause firefox to be swallowed by your terminal. I use that keybind myself to selectively choose when to swallow an application window I'm about to spawn. Does that help you?

Oh, and the obvious question: How do you spawn terminals since these are also just regular gui applications themselves? Aren't they affected by your problem?

**Comment by Coalms** [comment]
@slavistan The acute loop of life you are living through,a painful kind of professionalism,but then again you have to somehow satisfying the masses ,and having a clean and throughout github certainly does the trick.

I don't really remember what I was reading at the time it was probably "Who left the bag of Idiots open",other than that right now I picked up Good Omens but hadn't had time to read it yet.

While the reason of why windows spawn invisible is unknown spawning a terminal through dwm isn't  a problem,certainly I was lucky,but then again I can only use xfce4-terminal for that reason -.-  ,there are a few other programs as well that don't get stage fright when spawned but when they do,I don't know anymore if they are open or not even after a force close of the invisible window....

That being I hadn't have it in mind to switch zsh to vi mode,didn't even cross my mind I should do and try it the next couple of hours

Other than that I did try to make a half-assed script when I got out of bed thinking eureka.....for the simplest line of script,don't make fun of me here .this hadn't crossed my mind until that point 

```
toswallow=(firefox Zathura Godot Thunar)
namediffr=(NULL    NULL    NULL  NULL  )
	#the swallow for array loop
for swallowed in ${toswallow[@]}; do name=$(echo $swallowed | tr '[:upper:]' '[:lower:]');alias $name="dwmswallow $WINDOWID -c $swallowed && $name"; done; 
```
the only think that's missing is after && to check if namediffr !=null,if it is then `&& namediffr[number]` else` $name` and after this could also get used by your script as well if there was a way to automatically get wm_class

Closing up I would like to say that if you ever find an Exstensa 560Z being given away/in a yard sale/in the bin then set it on fire and watch it burn and then psalm [this](https://www.youtube.com/watch?v=5VHHgbWyGu0) and if you are wondering why such hatred I would like to say my computer,where I was forced to use the most lightweight programs possible ,froze in the middle of writing this and closing dwm command didnt respond so I had to force shut down,and my cookies didn't keep this whole thing like they usually do,so I HAD TO REWRITE IT,fuck I can't even complain its a laptop from like 2008
