### ISSUE TITLE
Using dwmswallow with omitted filter under zsh can cause infinite loop

### ISSUE THREAD

**Issue by takd** [slavistan/dwm-dynamicswallow-patch#2]
Observed behaviour:
Running `dwmswallow $WINDOWID; zathura file.pdf` per the tutorial in a zsh shell sometimes causes an infinite loop in dwm: cpu usage goes to 100%, dwm becomes unresponsive. Furthermore, zathura does not open at all. (This is not related to zathura, this was tested with other programs as well, such as mpv.)

Running the same in bash works perfectly every time.

Running dwm in gdb shows that the infinite loop is in the function `drawbar`. Seems like maybe the the `c->next` linked list somehow became a loop.

Steps to reproduce:
- apply patch to dwm 61bb8b2
- open terminal with zsh
- run `dwmswallow $WINDOWID; zathura file.pdf`

System: Manjaro, terminal: xfce4-terminal.

**Comment by slavistan** [comment]
Hi!

I cannot reproduce the problem, neither with my build nor with a freshly patched dwm (61bb8b2) on my Ubuntu system with neither `st` nor `xfce4-terminal`.

What's suspicious is that your interactive shell should make no difference whatsoever, as `dwmswallow` is executed by `sh`, as per its shebang *#!/usr/bin/env sh* in the first line (`dwmswallow` is a simple shell script). Whether you're using bash or zsh when you call `dwmswallow $WINDOWID; zathura file.pdf` is irrelevant.

May I kindly ask you to poke around some more? Try some shotgun debuggung, e.g. Remove the section from **drawbar()** which draws the swallow symbol and update `zsh`.

**Comment by takd** [comment]
Hi, thanks for the suggestions!

Though I did investigate the issue thoroughly before posting this issue, now I cannot reproduce it in any way. Really weird, I did the exact same things. Hope it will work now then! Will report back if I detect it again.
